export const manualToken =
    
    
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2Y1NDQxOWIxYTViZTIyNzc2ODQxOSIsImlhdCI6MTcxOTg3MjEyMywiZXhwIjoxNzE5OTU4NTIzfQ.CPG_10U2zD2ddkuPNL5gSgJhpkuygQWkxJCiq6ryGH8'
