export const data = {
  transactionsType: [
    {
      type: "Despesa Variável",
      categories: [
        "Restaurante",
        "Sorveteria",
        "Lanches",
        "Educação",
        "Transporte",
        "Farmácia",
        "Reparos em Casa",
        "Lazer",
        "Viagens",
        "Presentes",
        "Outros",
      ],
    },
    {
      type: "Receita Variável",
      categories: [
        "Freelancer",
        "Serviços",
        "Vendas",
        "Dividendos",
        "Comissões",
        "Divisão de Lucros",
        "Outros",
      ],
    },
    {
      type: "Despesa Fixa",
      categories: [
        "Aluguel/Moradia",
        "Financiamento Imóvel",
        "Condomínio",
        "Água",
        "Energia",
        "Internet",
        "Telefone",
        "Celular",
        "Assinaturas",
        "Seguros",
        "Prestação de Empréstimos",
        "Plano de Saúde",
        "Educação",
        "Impostos",
        "Entretenimento",
        "Outros",
      ],
    },
    {
      type: "Receita Fixa",
      categories: [
        "Salário",
        "Benefícios",
        "Pensão",
        "Rendimentos Fixos",
        "Dividendos",
        "Aluguéis",
        "Outros",
      ],
    },
    {
      type: "Investimentos",
      categories: [
        "REITs",
        "Stocks",
        "ETFs",
        "Criptomoedas",
        "Ações",
        "FIIs",
        "Fundos de Investimento",
        "Tesouro Direto",
        "CDB",
        "LCA/LCI",
        "Debentures",
        "Commodities",
        "PGBL/VGBL",
        "Poupança",
        "Outros",
      ],
    },
  ],
};

// 1: "😒 DV",
// 2: "😍 RV",
// 3: "😿 DF",
// 4: "🤑 RF",
// 5: "💹 Inv",
// };
